sequenceDiagram
    participant User
    participant Field
    participant API
    Note right of Field: Start with empty BEL Subject or Object field
    User->>Field: Focuses on Field
    Field->>API: BEL Completion Request (BCR), text='', cursor_loc=0, bel_format=short, bel_version=2.0.0, species=TAX:9606
    API->>Field: completions=[list of BEL functions]
    User->>Field: Types 'p', cursor_loc=1
    Field->>API: BCR, text='p'
    Note right of Field: completions result is actually list of objects with proposed completion value, highlighted match in function name/namespace/synonym, field replacement text with inserted completion_value, new cursor_loc
    API->>Field: completions=['p()','path()'] for proteinAbundance or pathology
    User->>Field: selects p()
    Field->>Field: p() inserted into field, replacing 'p', cursor moves inside ()
    Field->>API: BCR, text='p()', cursor_loc=2
    Note right of Field: when inside function arguments section, also provide function help - function schematics and argument descriptions
    API->>Field: completions: [fusion()], parent_function_help
    User->>Field: Add 'E'
    Field->>API: BCR, text="p(E)", cursor_loc=3
    API->>Field: completions=[''], removes fusion() since it doesn't match anymore
    Note right of API: API won't return a BEL Namespace completion until 3 chars are provided
    User->>Field: Add 'GF'
    Field->>API: BCR, text="p(EGF)", cursor_loc=5
    API->>Field: completions=['HGNC:EGF',"HGNC:EGFL6", ...]
    User->>Field: selects HGNC:EGF
    Field->>Field: replace input text with p(HGNC:EGF), move cursor after function
    User->>Field: user inserts cursor before ')' and inserts ,
    Field->>API: BCR, text="p(HGNC:EGF,)"
    API->>Field: completions=['pmod()', 'var()', 'loc()', 'frag()']
    User->>Field: selects pmod()



